name: CI

env:
  BUILD_TYPE: Debug Release

on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang++, g++]
        standard: [17, 20]
        config: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          git clone --branch 2024.07.12 --depth 1 https://github.com/microsoft/vcpkg "$HOME/vcpkg"
          export VCPKG_ROOT="$HOME/vcpkg"
          cmake --preset ci-${{ matrix.config }} -B build -DCMAKE_CXX_STANDARD=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        run: cmake --build build -j 8
      - name: Unit Tests
        run: |
          ctest --output-on-failure --test-dir build
      - name: Examples
        run: |
          find build -type f -executable -exec {} \;
  ubuntu-shared:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang++, g++]
        check_abi_compatibility: [OFF, ON]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
          export VCPKG_ROOT="$HOME/vcpkg"
          cmake --preset ci-release -B build -DYOMM2_SHARED=1 -DYOMM2_CHECK_ABI_COMPATIBILITY=${{ matrix.check_abi_compatibility }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        run: cmake --build build -j 8
      - name: Unit Tests
        run: YOMM2_TRACE=1 ctest --output-on-failure --test-dir build
      - name: Examples
        run: YOMM2_TRACE=1 find build -type f -executable -exec {} \;
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
        standard: [17, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: |
          git clone https://github.com/microsoft/vcpkg "$env:USERPROFILE/vcpkg"
          $env:VCPKG_ROOT = "$env:USERPROFILE/vcpkg"
          cmake --preset ci-${{ matrix.config }} -DCMAKE_CXX_STANDARD=${{ matrix.standard }} -B build
      - name: Build
        run: |
          cl
          cmake --build build -j 8
      - name: Unit Tests
        run: |
          $env:YOMM2_TRACE = 1
          ctest --output-on-failure --test-dir build
          $global:LASTEXITCODE = 0
  windows-shared:
    strategy:
      matrix:
        check_abi_compatibility: [OFF, ON]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
      - name: Configure
        run: |
          git clone https://github.com/microsoft/vcpkg "$env:USERPROFILE/vcpkg"
          $env:VCPKG_ROOT = "$env:USERPROFILE/vcpkg"
          cmake --preset ci-release -DYOMM2_SHARED=1 -DYOMM2_CHECK_ABI_COMPATIBILITY=${{ matrix.check_abi_compatibility }} -B build
      - name: Build
        run: cmake --build build -j 8
      - name: Unit Tests
        run: |
          $env:YOMM2_TRACE = 1
          $env:PATH += ";" + (Get-Item .).FullName + "/build/src"
          ctest --output-on-failure --test-dir build
          $global:LASTEXITCODE = 0
  mac:
    runs-on: macOS-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
          export VCPKG_ROOT="$HOME/vcpkg"
          cmake --preset ci-${{ matrix.config }} -B build
      - name: Build
        run: cmake --build build -j 8
      - name: Unit Tests
        run: |
          ctest --output-on-failure --test-dir build
      - name: Examples
        run: |
          find build -type f -perm +0111 -exec {} \;
